### ISSUE TITLE
Correct rendering of custom characters between words

### ISSUE THREAD

**Issue by 1mehdifaraji** [dalirnet/rtl-markdown#6]
When I want to put some special characters like ```*``` to make the word bold , it will overflow and display the text badly like this :

![Screenshot 1402-03-01 at 14 34 19](https://github.com/dalirnet/rtl-markdown/assets/63982703/af85670a-99a4-4bfa-9742-6189ad4d1d53)

But it's rendered correctly with macos ```Notes``` app like this :

![Screenshot 1402-03-01 at 14 35 02](https://github.com/dalirnet/rtl-markdown/assets/63982703/32409473-ed66-401c-a96a-283a9bd7e462)

I'm using ```vscode-insiders``` and extension version ```0.0.10```

**Comment by dalirnet** [comment]
@1mehdifaraji
I will review that next week.

**Comment by dalirnet** [comment]
Hello, @1mehdifaraji

This issue is related to your font. As you can see below, using a font that properly supports Persian letters will automatically resolve the issue.

```json
{
    "editor.fontFamily": "'Fira Code', Menlo, Monaco, 'Courier New', monospace"
}
```
![Incorrect](https://github.com/dalirnet/rtl-markdown/assets/7668289/5262c3f5-2697-45ff-bea0-38ce6bb68aac)

```json
{
    "editor.fontFamily": "Menlo, Monaco, 'Courier New', monospace"
}
```
![Correct](https://github.com/dalirnet/rtl-markdown/assets/7668289/d21a11b9-cbb2-4389-9075-b4e19af838b4)
