### ISSUE TITLE
Automatically detect RTL characters and align right?

### ISSUE THREAD

**Issue by GrimPixel** [dalirnet/rtl-markdown#7]
In a table, where LTR and RTL texts occupy different cells. I would like to see RTL texts aligned right in the preview while keeping LTR texts unchanged. Is it viable?

**Comment by dalirnet** [comment]
In general, it's not possible to mix RTL and LTR in the same document because the plugin changes the editor's direction globally.

However, you can use the trick below to change the text direction:

```md
| LTR     | RTL                            |
| ------- | ------------------------------ |
| 123 456 | <span dir="rtl">123 456</span> |
| ۱۲۳ ۴۵۶ | <span dir="rtl">۱۲۳ ۴۵۶</span> |
```
👇
| LTR     | RTL                            |
| ------- | ------------------------------ |
| 123 456 | <span dir="rtl">123 456</span> |
| ۱۲۳ ۴۵۶ | <span dir="rtl">۱۲۳ ۴۵۶</span> |

**Comment by GrimPixel** [comment]
Thanks. I was trying to avoid HTML there. I will seek other options.
